proyecto/productos/urls.py
from django.urls import path
from.import views

app_name="productos"

urlpatterns = [
    path('admin/listado', views.AdminListadoProductos.as_view(), name="adm_listado_productos"),
    path('admin/nuevo', views.NuevoProducto.as_view(), name="adm_nuevo_producto"),
    path('admin/editar/<int:pk>', views.EditarProducto.as_view(), name="editar"),
    path('me-gusta/<int:id_producto>', views.dar_mg, name="dar_mg"),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views 

from.import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name="inicio"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.logout_then_login, name="logout"),

     #includes
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuarios.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

proyecto/usuarios/urls.py
from django.urls import path
from.import views

app_name="usuarios"

urlpatterns = [
    path('registro', views.Registro.as_view(), name="registro"),
]

proyecto/categorias/models.py
from django.db import models

class Categoria(models.Model):
    nombre=models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    

proyecto/productos/models.py
from django.db import models

from categorias.models import Categoria
from usuarios.models import Usuario

class Producto(models.Model):
    nombre=models.CharField(max_length=255)
    precio=models.DecimalField(max_digits=6, decimal_places=2)
    descripcion=models.TextField()

    activo=models.BooleanField(default=True)

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, related_name="categorias", blank=True)

    categoria2 = models.ManyToManyField(Categoria)

    #ficha = models.OneToOneField(Ficha)  para los casos de 1 a 1 (a un producto le corresponde una ficha); se deberia crear el modelo Ficha

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name="productos", blank=True)

    imagen = models.ImageField(upload_to="productos", null=True, blank=True)
    #tambien existe archivo = models.FileField

    def __str__(self):
        return self.nombre

class MeGusta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

"""
c = Categoria.objects.get(id=1)
c.categorias.all()

#crear tabla intermedia de forma manual: 
class ProductoCategoria(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    # fecha
"""

proyecto/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    es_admin=models.BooleanField(default=False)
    

proyecto/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    nombre=  forms.CharField(label="Nombre", widget=forms.TextInput(attrs={"class":"form-control"}))
    descripcion = forms.CharField(label="Descripcion", widget=forms.TextInput(attrs={"class":"form-control"}))
  
    
    class Meta:
        model=Producto
        fields=["nombre", "descripcion", "precio", "activo", "categoria", "categoria2", "imagen"]
    
    def clean_precio(self):
        precio = self.cleaned_data["precio"]
        if precio <= 0:
            raise forms.ValidationError("el precio debe ser un numero positivo")
        return precio

proyecto/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


from .models import Usuario

class UsuarioForm(UserCreationForm):
    first_name=forms.CharField(label="Nombre", widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name=forms.CharField(label="Apellido", widget=forms.TextInput(attrs={"class":"form-control"}))
    email=forms.CharField(label="e-mail", widget=forms.TextInput(attrs={"class":"form-control"}))
    username=forms.CharField(label="Nombre de Usuario", widget=forms.TextInput(attrs={"class":"form-control"}))
    password1=forms.CharField(label="Contraseña", widget=forms.TextInput(attrs={"class":"form-control"}))
    password2=forms.CharField(label="Confirmar", widget=forms.TextInput(attrs={"class":"form-control"}))

    class Meta:
        model= Usuario
        fields=["first_name", "last_name", "email", "username", "password1", "password2"]

proyecto/categorias/views.py
from django.shortcuts import render

# Create your views here.

proyecto/productos/views.py
from django.shortcuts import render 
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse

from django.http import HttpResponseRedirect
from .forms import ProductoForm
from .models import Producto, MeGusta

from django.contrib.auth.mixins import LoginRequiredMixin

from utilidades.mixins import IsAdminMixins


"""
def adm_listado_productos(request):
    template_name = 'productos/listado.html'

    contexto = {
        'productos': Producto.objects.all()
    }
    return render(request, template_name, contexto)
"""


class AdminListadoProductos (LoginRequiredMixin, IsAdminMixins, ListView):
    template_name = "productos/listado.html"
    model = Producto
    context_object_name = "productos"
    paginate_by = 3

    def get_queryset(self):
        productos = Producto.objects.all()
        nombre_producto = self.request.GET.get("buscador")
        if nombre_producto:
            productos = productos.filter(nombre__contains=nombre_producto)
        return productos.order_by("nombre")


class NuevoProducto(CreateView):
    model= Producto
    template_name = "productos/nuevo_producto.html"
    form_class = ProductoForm

    def get_success_url(self):
        return reverse("productos:adm_listado_productos")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context["producto"] = Producto.objects.get(id=3)
        return context
    
    def form_valid(self, form):
        f = form.save(commit=False)
        f.usuario_id = self.request.user.id
        return super(NuevoProducto, self).form_valid(form)
    


class EditarProducto(UpdateView):
    model= Producto
    template_name = "productos/editar.html"
    form_class = ProductoForm

    def get_success_url(self):
        return reverse("productos:adm_listado_productos")

def dar_mg(request, id_producto):
    mg = MeGusta.objects.filter(usuario=request.user, producto__id=id_producto)
    if not mg:
        mg = MeGusta.objects.create(usuario=request.user, producto=Producto.objects.get(id=id_producto))
    return HttpResponseRedirect(reverse("inicio"))

proyecto/proyecto/views.py
from django.shortcuts import render 

from django.contrib.auth.decorators import login_required

from utilidades.mixins import is_admin_required

from productos.models import Producto

@is_admin_required()
def inicio(request):
    template_name = 'index.html'

    """"
    p=Producto.objects.create(
        nombre="pantalon",
        precio=1500,
        descripcion="pantalaon azul"
    )
    """

    
    
    contexto = {
        'productos': Producto.objects.filter(activo=True)
    }
    return render(request, template_name, contexto)

"""
def login(request):
    print("entre al login")
    print(request.GET["password"])

    return render(request, "login.html",{})
"""

proyecto/usuarios/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse

from .forms import UsuarioForm 
from. models import Usuario

class Registro(CreateView):
    model= Usuario
    template_name = "usuarios/registro.html"
    form_class = UsuarioForm

    def get_success_url(self):
        return reverse("login")

proyecto/templates/base/base.html
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Tienda en linea</title>

    <!-- Css only-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    {% block css_extras %}
    {% endblock css_extras %}
</head>

<body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">Nosotros</h4>
                        <p class="text-light">Tienda de ropa unisex de talles reales!</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contactos</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Twitter</a></li>
                            <li><a href="#" class="text-white">Facebook</a></li>
                            <li><a href="#" class="text-white">e-mail</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true"
                        class="bi bi-cart4" viewBox="0 0 18 18">
                        <path
                            d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z">
                        </path>
                    </svg>
                    <strong>Tienda</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>
    <main>
        <section id= "seccion_index" class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">LISTA DE PRODUCTOS</h1>
                    <p class="lead text-muted">todos los productos. Hola {{ user.username }} !</p>
                    <p>
                        {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="btn btn-primary my-2">Cerrar sesion</a>
                        {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary my-2">Iniciar sesion</a>
                        <a href="#" class="btn btn-secondary my-2">Crear una cuenta</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </section>
        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row">
                    <nav class="navbar navbar-expand-lg bg-light">
                        <div class="container-fluid">
                            <a class="navbar-brand" href="#">Tienda</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="nav-link active" aria-current="page"
                                            href="{% url 'inicio' %}">Inicio</a>
                                    </li>

                                    {% if user.es_admin %}

                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'productos:adm_listado_productos' %}">Productos</a>
                                    </li>

                                    {% endif %}

                                    <!--
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" role="button"
                                            data-bs-toggle="dropdown" aria-expanded="false">
                                            Dropdown
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="#">Action</a></li>
                                            <li><a class="dropdown-item" href="#">Another action</a></li>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link disabled">Disabled</a>
                                    </li>
                                    -->
                                </ul>
                                <form class="d-flex" role="search" method="get">
                                    <input class="form-control me-2" type="search" placeholder="Encuentra tu producto"
                                        aria-label="Search" name="buscador">
                                    <button class="btn btn-outline-primary" type="submit">Buscar</button>
                                </form>
                            </div>
                        </div>
                    </nav>
                </div>
                {% block contenido %}
                {% endblock contenido %}
            </div>
        </div>

    </main>

    <footer class="text-muted py-5">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#">Volver arriba</a>
            </p>
            <p class="mb-1">Catalogo © Marcos</p>
            <p class="mb-0">Comentario <a href="/">enlace 1</a> comentario <a
                    href="/docs/5.3/getting-started/introduction/">enlace 2</a>.</p>
        </div>
    </footer>

    <!-- Js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
        </script>

    {% block js_extras %}
    {% endblock js_extras %}
</body>

</html>

proyecto/templates/incluidos/errores_form.html
{% if form.errors %}
{% for field in form%}
{% for error in field.errors %}
<div class="alert alert-danger" role="alert">
    {{field.label}} : {{error|safe}}
</div>
{% endfor%}
{% endfor%}

{% for error in form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {{error|safe}}
</div>
{% endfor%}
{% endif%}

proyecto/templates/incluidos/paginado.html
{% if is_paginated %}
<nav>
    <ul class="pagination pagination-circle mg-b-0 justify-content-center">
        {% if page_obj.number == 1 %}
            <li class="page-item disabled"><a class="page-link">inicio</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page=1">inicio</a></li>
        {% endif %}

        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">volver</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">volver</a></li>
        {% endif %}

        {% for i in paginator.page_range %}
            {% if page_obj.number|add:'-1' <= i and page_obj.number|add:'1' >= i %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
            {% else %}

            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">siguiente</a></li>
        {% endif %}

        {% if page_obj.number == paginator.num_pages %}
            <li class="page-item disabled"><a class="page-link">fin</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}">fin</a></li>
        {% endif %}

    </ul>
</nav>
{% endif %}

proyecto/templates/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block css_extras %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
{% endblock css_extras %}

{% block contenido %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in productos %}
    <div class="col">
        <div class="card shadow-sm">
            {% if p.imagen %}
                <img src="{{p.imagen.url}}" class="bd-placeholder-img card-img-top" width="100%" height="450">
            {% else %}
            <svg  xmlns="http://www.w3.org/2000/svg"
                role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Imagen de Producto</title>
                <rect width="100%" height="100%" fill="#55595c"></rect><text x="30%" y="50%" fill="#eceeef"
                    dy=".3em">Actualizando foto</text>
            </svg>
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{p.nombre}} <span class="badge bg-secondary">${{ p.precio}}</span><span class="badge text-bg-danger">{{p.categoria.nombre}}</span>
                </h5>
                <p class="card-text">{{p.descripcion}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% for c in p.categoria2.all %}
                            <span class="badge text-bg-danger">{{c.nombre}}</span>
                        {% endfor %}
                    </div>
                    <small class="text-muted"><a type="button" class="btn btn-info" href="{% url 'productos:dar_mg' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                      </svg></a></small>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="alert alert-primary" role="alert">
        <h4 class="alert-heading">Hola!</h4>
        <p>Estamos actualizando nuestra lista de productos...</p>
        <hr>
        <p class="mb-0">Ingresa en otro momento ♥</p>
    </div>
    {% endfor %}


</div>

{% endblock contenido %}

proyecto/templates/login.html
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="generator" content="Hugo 0.108.0">
    <title>INICIAR SESION</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>

<body class="text-center">

    <main class="form-signin w-100 m-auto">
        <form method="post">{% csrf_token %}
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-bag-heart"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5Zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0ZM14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1ZM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
            </svg>
            <h1 class="h3 mb-3 fw-normal">Ingresar</h1>

             {%  include 'incluidos/errores_form.html' %}

            <div class="form-floating">
                <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
                <label for="floatingInput">Nombre de usuario</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                <label for="floatingPassword">Contraseña</label>
            </div>

            <br>
            <p><button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button></p>
            <p><a class="w-100 btn btn-lg btn-primary" href="{% url 'inicio' %}">Volver</a></p>
            <a class="w-100 btn btn-lg btn-primary" href="{% url 'usuarios:registro' %}">Registrarte</a>
            <p class="mt-5 mb-3 text-muted">© Marcos</p>

        </form>
    </main>





</body>

</html>

proyecto/templates/productos/editar.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{form.as_p}}
    <p><button class="w-100 btn btn-lg btn-primary" type="submit">Guardar</button></p>
    <p><a class="w-100 btn btn-lg btn-primary" href="{% url 'productos:adm_listado_productos' %}">Cancelar</a></p>
</form>
{% endblock contenido %}

proyecto/templates/productos/listado.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="row">
    <div class="col">    
        <a type="button" class="btn btn-outline-primary" href="{% url 'productos:adm_nuevo_producto' %}">Agregar producto</a>
    </div>
</div><br>
<div class="card">
    <div class="card-header">
        Lista de productos
    </div>
    <div class="card-body">
        <table class="table table-primary table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">nombre</th>
                    <th scope="col">precio</th>
                    <th scope="col">descripcion</th>
                    <th scope="col">categoria</th>
                
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for p in productos %}
                <tr>
                    <th scope="row">{{p.id}}</th>
                    <td>{{p.nombre}}</td>
                    <td>${{p.precio}}</td>
                    <td>{{p.descripcion}}</td>
                    <td>
                        {% for c in p.categoria2.all %}
                            {{ c }}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'productos:editar' p.id %}" class="btn btn-info">Editar</a>
                        <button type="button" class="btn btn-dark">Eliminar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        {% include 'incluidos/paginado.html' %}
    </div>
</div>


{% endblock contenido %}

proyecto/templates/productos/nuevo_producto.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{form.as_p}}

    <p><button class="w-100 btn btn-lg btn-primary" type="submit">Crear</button></p>
</form>
{% endblock contenido %}

proyecto/templates/usuarios/registro.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="card">
    <div class="card-body">
        <form method="post">{% csrf_token %}
      {{ form.as_p }}
            <button type="submit" class="btn btn-primary my-2">Crear</button>
      </form>
    </div>
  </div>
{% endblock contenido %}